"""CropFusion release runtime (Phase R6).

A production-grade runtime that loads, validates and serves a **release
package** generated by the training platform. The runtime consumes only
exported artefacts — the Kaggle catalog, the dataset manager and the training
loop are never required.

Components:

* :class:`ReleasePackager` — turns the Phase R5 inference package into the
  canonical ``cropfusion_release-<version>/`` layout.
* :class:`ReleaseManager` — discovers, validates, activates and rolls back
  releases under the releases root.
* :class:`ModelLoader` — loads the PyTorch / TorchScript / ONNX model, its
  config, metadata and version, and warms it up.
* :class:`PreprocessLoader` — loads ``feature_scalers.pkl`` /
  ``label_encoder.pkl``.
* :class:`MetadataLoader` — opens ``metadata.db`` and the context / location /
  feature-lookup parquets.
* :class:`ReleaseValidator` — checksums, manifest, versions, dependencies,
  compatibility and a smoke test.
* :class:`InferenceRuntime` — the orchestrator (init / load / validate /
  warmup / health / shutdown / reload / rollback).
* :class:`HealthReport` / :class:`MemoryMonitor` — readiness + memory state.
"""

from __future__ import annotations

from .cache import RuntimeCache
from .config import (
    CacheConfig,
    GeneralConfig,
    HealthConfig,
    HotReloadConfig,
    MemoryConfig,
    MetadataConfig,
    ModelLoadConfig,
    PreprocessConfig,
    RuntimeConfig,
    ValidationConfig,
    load_runtime_config,
    save_runtime_template,
)
from .exceptions import (
    DependencyError,
    HealthError,
    MemoryLimitError,
    MetadataLoadError,
    ModelLoadError,
    ModelWarmupError,
    PreprocessLoadError,
    ReleaseActivationError,
    ReleaseError,
    ReleaseLayoutError,
    ReleaseNotFoundError,
    ReleasePackagingError,
    ReleaseRollbackError,
    ReleaseValidationError,
    RuntimeConfigurationError,
    RuntimeEnvironmentError,
)
from .health import (
    STATUS_DEGRADED,
    STATUS_LOADING,
    STATUS_NOT_READY,
    STATUS_READY,
    HealthReport,
    MemoryInfo,
    MemoryMonitor,
)
from .layout import (
    FORMAT_FILES,
    RELEASE_DIRS,
    RELEASE_DIR_PREFIX,
    REQUIRED_RELEASE_FILES,
    ReleaseInfo,
    ReleaseLayout,
    ReleaseManifest,
    parse_release_dir,
    release_dir_name,
)
from .metadata_loader import MetadataHealth, MetadataLoader
from .model_loader import ModelHealth, ModelLoader
from .packager import ReleasePackager, ReleaseReport
from .preprocess_loader import PreprocessHealth, PreprocessLoader
from .release_manager import ReleaseManager, RuntimeState
from .runtime import InferenceRuntime
from .validation import (
    ReleaseValidationResult,
    ReleaseValidator,
)

__version__ = "0.1.0"

__all__ = [
    # Config
    "RuntimeConfig",
    "GeneralConfig",
    "ModelLoadConfig",
    "PreprocessConfig",
    "MetadataConfig",
    "CacheConfig",
    "MemoryConfig",
    "HealthConfig",
    "HotReloadConfig",
    "ValidationConfig",
    "load_runtime_config",
    "save_runtime_template",
    # Layout
    "ReleaseLayout",
    "ReleaseManifest",
    "ReleaseInfo",
    "RELEASE_DIRS",
    "RELEASE_DIR_PREFIX",
    "REQUIRED_RELEASE_FILES",
    "FORMAT_FILES",
    "parse_release_dir",
    "release_dir_name",
    # Packaging
    "ReleasePackager",
    "ReleaseReport",
    # Release manager
    "ReleaseManager",
    "RuntimeState",
    # Loaders
    "ModelLoader",
    "ModelHealth",
    "PreprocessLoader",
    "PreprocessHealth",
    "MetadataLoader",
    "MetadataHealth",
    # Validation
    "ReleaseValidator",
    "ReleaseValidationResult",
    # Health
    "HealthReport",
    "MemoryMonitor",
    "MemoryInfo",
    "STATUS_READY",
    "STATUS_DEGRADED",
    "STATUS_LOADING",
    "STATUS_NOT_READY",
    # Cache
    "RuntimeCache",
    # Runtime
    "InferenceRuntime",
    # Exceptions
    "RuntimeEnvironmentError",
    "RuntimeConfigurationError",
    "ReleaseError",
    "ReleaseNotFoundError",
    "ReleaseLayoutError",
    "ReleaseValidationError",
    "ReleaseActivationError",
    "ReleaseRollbackError",
    "ReleasePackagingError",
    "ModelLoadError",
    "ModelWarmupError",
    "PreprocessLoadError",
    "MetadataLoadError",
    "DependencyError",
    "MemoryLimitError",
    "HealthError",
]
