"""Build a static HTML documentation site from Markdown sources.

Used by ``Dockerfile.docs`` and for local previews::

    python scripts/build_docs.py --source docs --output build/docs

Only depends on the stdlib plus the ``markdown`` and ``pygments`` packages.
"""

from __future__ import annotations

import argparse
import html
import shutil
import sys
from pathlib import Path

try:
    import markdown as md
except ImportError:  # pragma: no cover - CI installs it
    md = None


SKIP = {"manuals", "website", "releases"}
STYLES = """
:root { --accent:#2f7d32; --bg:#ffffff; --fg:#1f2937; --muted:#6b7280; --border:#e5e7eb; }
* { box-sizing:border-box; }
body { font-family:-apple-system,'Segoe UI',Roboto,Helvetica,Arial,sans-serif; margin:0;
       color:var(--fg); background:var(--bg); line-height:1.6; }
header { background:#0f3d13; color:#fff; padding:18px 32px; }
header h1 { margin:0; font-size:20px; }
header span { font-weight:normal; color:#9fd3a2; font-size:13px; }
nav { border-bottom:1px solid var(--border); padding:10px 32px; background:#f9fafb; }
nav a { color:var(--accent); text-decoration:none; margin-right:18px; font-size:14px; }
main { max-width:880px; margin:0 auto; padding:28px 32px 64px; }
main img { max-width:100%; }
pre { background:#f6f8fa; border:1px solid var(--border); border-radius:6px; padding:12px; overflow-x:auto; }
code { background:#f1f3f5; border-radius:4px; padding:1px 5px; font-size:0.92em; }
pre code { background:none; padding:0; }
table { border-collapse:collapse; width:100%; margin:16px 0; }
th, td { border:1px solid var(--border); padding:8px 12px; text-align:left; }
th { background:#f9fafb; }
h1, h2, h3 { color:#0f3d13; }
blockquote { border-left:4px solid var(--accent); margin:0; padding:2px 16px; background:#f3f8f3; }
footer { border-top:1px solid var(--border); color:var(--muted); text-align:center; padding:16px; font-size:12px; }
"""

TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title} - CropFusion</title>
<style>{styles}</style>
</head>
<body>
<header><h1>CropFusion <span>{nav}</span></h1></header>
<nav>{crumbs}</nav>
<main>{body}</main>
<footer>Generated by scripts/build_docs.py &middot; {date}</footer>
</body>
</html>
"""


def render_markdown(text: str) -> str:
    if md is not None:
        return md.markdown(
            text,
            extensions=["fenced_code", "tables", "codehilite", "toc", "nl2br"],
            output_format="html5",
        )
    return f"<pre>{html.escape(text)}</pre>"


def toc(files: list[Path]) -> str:
    links = []
    for path in files:
        rel = path.as_posix()
        label = path.stem.replace("_", " ").title()
        links.append(f'<a href="{html.escape(rel)}.html">{html.escape(label)}</a>')
    return " ".join(links)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", default="docs", help="docs root")
    parser.add_argument("--output", default="build/docs", help="output dir")
    args = parser.parse_args()

    source = Path(args.source)
    output = Path(args.output)
    output.mkdir(parents=True, exist_ok=True)

    files = sorted(
        p
        for p in source.rglob("*.md")
        if not any(part in SKIP for part in p.parts)
    )

    for path in files:
        relative = path.relative_to(source)
        dest = output / relative.with_suffix(".html")
        dest.parent.mkdir(parents=True, exist_ok=True)
        body = render_markdown(path.read_text(encoding="utf-8"))
        crumbs = " / ".join(html.escape(part) for part in relative.parts[:-1]) or "Home"
        dest.write_text(
            TEMPLATE.format(
                title=relative.stem.replace("_", " ").title(),
                nav="Documentation",
                crumbs=crumbs,
                body=body,
                styles=STYLES,
                date=__import__("datetime").date.today().isoformat(),
            ),
            encoding="utf-8",
        )

    (output / "index.html").write_text(
        TEMPLATE.format(
            title="Documentation Index",
            nav="Documentation",
            crumbs="Home",
            body="<h1>Documentation</h1><ul>"
            + "".join(
                f'<li><a href="{html.escape(p.relative_to(source).as_posix())}.html">'
                f"{html.escape(p.relative_to(source).stem.replace('_', ' ').title())}</a></li>"
                for p in files
            )
            + "</ul>",
            styles=STYLES,
            date=__import__("datetime").date.today().isoformat(),
        ),
        encoding="utf-8",
    )
    assets = source / "assets"
    if assets.is_dir():
        shutil.copytree(assets, output / "assets", dirs_exist_ok=True)
    print(f"built {len(files)} pages -> {output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
